#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Language {
    En,
    Tr,
}

impl Language {
    pub fn from_config(value: &str) -> Language {
        match value.trim().to_ascii_lowercase().as_str() {
            "tr" | "turkish" | "turkce" => Language::Tr,
            _ => Language::En,
        }
    }

    pub fn code(self) -> &'static str {
        match self {
            Language::En => "en",
            Language::Tr => "tr",
        }
    }

    pub fn strings(self) -> &'static Strings {
        match self {
            Language::En => &EN,
            Language::Tr => &TR,
        }
    }
}

pub struct Strings {
    pub progress_bar: &'static str,
    pub search_local: &'static str,
    pub search_online: &'static str,
    pub local_files: &'static str,
    pub online_results: &'static str,
    pub sort_prefix: &'static str,
    pub queue: &'static str,
    pub queue_focused: &'static str,
    pub queue_empty: &'static str,
    pub more_suffix: &'static str,
    pub volume_bar: &'static str,
    pub play: &'static str,
    pub pause: &'static str,

    pub meta_name: &'static str,
    pub meta_artist: &'static str,
    pub meta_year: &'static str,
    pub meta_sampling: &'static str,
    pub meta_type: &'static str,
    pub meta_format: &'static str,
    pub meta_size: &'static str,
    pub meta_location: &'static str,
    pub meta_channels: &'static str,

    pub no_track: &'static str,
    pub fetching_lyrics: &'static str,
    pub no_lyrics: &'static str,
    pub resolving: &'static str,
    pub scanning: &'static str,
    pub no_music_path: &'static str,
    pub no_music_here: &'static str,
    pub yt_dlp_missing: &'static str,
    pub searching: &'static str,
    pub no_results: &'static str,
    pub download_started: &'static str,
    pub playlist_saved: &'static str,
    pub playlist_empty: &'static str,
    pub playlist_nowhere: &'static str,
    pub playlist_failed: &'static str,
    pub download_done: &'static str,
    pub settings_saved: &'static str,
    pub queued: &'static str,

    pub view_all: &'static str,
    pub view_liked: &'static str,
    pub view_played: &'static str,
    pub view_recent: &'static str,
    pub liked: &'static str,
    pub unliked: &'static str,
    pub help_title: &'static str,
    pub help_close: &'static str,
    pub help_mouse: &'static str,
    pub help_search: &'static str,
    pub help_search_online: &'static str,
    pub help_play: &'static str,
    pub help_pause: &'static str,
    pub help_skip: &'static str,
    pub help_seek: &'static str,
    pub help_volume: &'static str,
    pub help_modes: &'static str,
    pub help_queue: &'static str,
    pub help_panel: &'static str,
    pub help_reorder: &'static str,
    pub help_like: &'static str,
    pub help_view: &'static str,
    pub help_sort: &'static str,
    pub help_folder: &'static str,
    pub help_artist: &'static str,
    pub help_clear: &'static str,
    pub help_sleep: &'static str,
    pub help_playlist: &'static str,
    pub help_lyrics: &'static str,
    pub help_download: &'static str,
    pub help_settings: &'static str,
    pub help_help: &'static str,
    pub help_quit: &'static str,
    pub help_mouse_disk: &'static str,
    pub help_mouse_skip: &'static str,
    pub help_mouse_seek: &'static str,
    pub help_mouse_volume: &'static str,
    pub help_mouse_row: &'static str,
    pub help_mouse_queue: &'static str,
    pub help_mouse_scroll: &'static str,
    pub help_mouse_settings: &'static str,
    pub decode_failed: &'static str,
    pub lyric_shift: &'static str,
    pub sleep_off: &'static str,
    pub sleep_set: &'static str,
    pub sleep_done: &'static str,
    pub sort_name: &'static str,
    pub sort_artist: &'static str,
    pub sort_folder: &'static str,
    pub sort_recent: &'static str,
    pub mode_loop: &'static str,
    pub mode_shuffle: &'static str,
    pub mode_stop: &'static str,

    pub tab_colors: &'static str,
    pub tab_onoff: &'static str,
    pub tab_animation: &'static str,
    pub tab_eq: &'static str,
    pub tab_paths: &'static str,
    pub tab_reference: &'static str,
    pub tab_about: &'static str,
    pub settings_title: &'static str,
    pub settings_hint: &'static str,
    pub paths_hint: &'static str,
    pub paths_add: &'static str,
    pub paths_missing: &'static str,
    pub device_default: &'static str,
    pub eq_preset: &'static str,
    pub eq_hint: &'static str,

    pub grp_border: &'static str,
    pub grp_disk: &'static str,
    pub grp_metadata: &'static str,
    pub grp_viz: &'static str,
    pub grp_progress: &'static str,
    pub grp_list: &'static str,
    pub grp_queue: &'static str,
    pub grp_lyrics: &'static str,

    pub col_top: &'static str,
    pub col_bottom: &'static str,
    pub col_key: &'static str,
    pub col_val: &'static str,
    pub col_left: &'static str,
    pub col_right: &'static str,
    pub col_played: &'static str,
    pub col_pending: &'static str,
    pub col_inactive_fg: &'static str,
    pub col_playing_fg: &'static str,
    pub col_cursor_fg: &'static str,
    pub col_active_line_fg: &'static str,
    pub col_active_word_fg: &'static str,
    pub col_bg: &'static str,
    pub preview_sample: &'static str,
    pub preview_song: &'static str,
    pub preview_name: &'static str,
    pub preview_lyric_a: &'static str,
    pub preview_lyric_b: &'static str,
    pub preview_lyric_c: &'static str,

    pub onoff_rows: [&'static str; 9],
    pub anim_rows: [&'static str; 13],
    pub ref_rows: [&'static str; 11],
}

pub static EN: Strings = Strings {
    progress_bar: "PROGRESS BAR",
    search_local: "SEARCH LOCAL",
    search_online: "SEARCH ONLINE",
    local_files: "LOCAL AUDIO FILES",
    online_results: "ONLINE RESULTS",
    sort_prefix: "sort",
    queue: "QUEUE",
    queue_focused: "QUEUE (focused)",
    queue_empty: "ADD TRACKS TO QUEUE",
    more_suffix: "more",
    volume_bar: "VOLUME BAR",
    play: "PLAY",
    pause: "PAUSE",

    meta_name: "Name",
    meta_artist: "Artist",
    meta_year: "year",
    meta_sampling: "sampling",
    meta_type: "type",
    meta_format: "format",
    meta_size: "file size",
    meta_location: "location",
    meta_channels: "channels",

    no_track: "no track loaded - press / to search, Enter to play",
    fetching_lyrics: "fetching lyrics ...",
    no_lyrics: "no lyrics found",
    resolving: "resolving/downloading...",
    scanning: "scanning library...",
    no_music_path: "no music folder found - add LocalMusicPath to config.txt",
    no_music_here: "nothing found - press s, open PATHS and add a folder",
    yt_dlp_missing: "yt-dlp not found in PATH - online search disabled",
    searching: "searching...",
    no_results: "no results",
    download_started: "downloading...",
    playlist_saved: "tracks saved",
    playlist_empty: "nothing in the queue or the list to save",
    playlist_nowhere: "no music folder to save into",
    playlist_failed: "could not write the playlist",
    download_done: "saved to",
    settings_saved: "settings saved",
    queued: "queued",

    view_all: "all",
    view_liked: "liked",
    view_played: "played",
    view_recent: "recent",
    liked: "liked",
    unliked: "unliked",
    help_title: "KEYS",
    help_close: "any key closes",
    help_mouse: "MOUSE",
    help_search: "search the library",
    help_search_online: "search online",
    help_play: "play what is highlighted",
    help_pause: "play / pause",
    help_skip: "previous / next track",
    help_seek: "seek back / forward",
    help_volume: "volume down / up",
    help_modes: "shuffle / repeat",
    help_queue: "add to / drop from the queue",
    help_panel: "move between list and queue",
    help_reorder: "reorder the queue",
    help_like: "like the track",
    help_view: "all, liked, played, recent",
    help_sort: "sort by name, artist, folder, recent",
    help_folder: "only this folder",
    help_artist: "only this artist",
    help_clear: "clear search and filters",
    help_sleep: "sleep timer",
    help_playlist: "save the list as a playlist",
    help_lyrics: "shift the lyrics earlier / later",
    help_download: "save the stream",
    help_settings: "settings",
    help_help: "this screen",
    help_quit: "quit",
    help_mouse_disk: "click the cover to pause",
    help_mouse_skip: "previous / next",
    help_mouse_seek: "click or drag to seek",
    help_mouse_volume: "click or drag the volume",
    help_mouse_row: "click a row to select it",
    help_mouse_queue: "click again to play, right-click to queue",
    help_mouse_scroll: "wheel scrolls the list",
    help_mouse_settings: "open the settings",
    decode_failed: "could not decode that file",
    lyric_shift: "lyrics shifted",
    sleep_off: "sleep timer off",
    sleep_set: "sleeping in",
    sleep_done: "sleep timer reached",
    sort_name: "name",
    sort_artist: "artist",
    sort_folder: "folder",
    sort_recent: "recent",
    mode_loop: "repeat",
    mode_shuffle: "shuffle",
    mode_stop: "stop after",

    tab_colors: "COLORS",
    tab_onoff: "ON/OFF",
    tab_animation: "ANIMATION",
    tab_eq: "EQ",
    tab_paths: "PATHS",
    tab_reference: "REFERENCE",
    tab_about: "ABOUT APP",
    settings_title: "SETTINGS",
    settings_hint: "[TAB] Switch | [\u{2191}\u{2193}\u{2190}\u{2192}] Navigate/Cycle | [ENTER] Edit | [S] Save | [Q] Back",
    paths_hint: "[ENTER] Edit | [A] Add | [D] Remove | [R] Rescan | [S] Save | [Q] Back",
    paths_add: "+ add a folder or a playlist",
    paths_missing: "not found",
    device_default: "system default",
    eq_preset: "Preset",
    eq_hint: "[\u{2191}\u{2193}] Band | [\u{2190}\u{2192}] Gain | click the slider | [0] Flat | [S] Save | [Q] Back",

    grp_border: "BORDER_COLOR",
    grp_disk: "DISK",
    grp_metadata: "METADATA",
    grp_viz: "VIZ",
    grp_progress: "PROGRESS_BAR",
    grp_list: "LIST",
    grp_queue: "QUEUE",
    grp_lyrics: "LYRICS",

    col_top: "TOP",
    col_bottom: "BOTTOM",
    col_key: "KEY",
    col_val: "VAL",
    col_left: "LEFT",
    col_right: "RIGHT",
    col_played: "PLAYED",
    col_pending: "PENDING",
    col_inactive_fg: "INACTIVE  FG",
    col_playing_fg: "PLAYING   FG",
    col_cursor_fg: "CURSOR    FG",
    col_active_line_fg: "ACTIVE L  FG",
    col_active_word_fg: "ACTIVE W  FG",
    col_bg: "BG",
    preview_sample: "THIS IS AN EXAMPLE TEXT",
    preview_song: "SONG.MP3",
    preview_name: "NAME : ",
    preview_lyric_a: "THIS IS ",
    preview_lyric_b: "AN ",
    preview_lyric_c: "EXAMPLE TEXT",

    onoff_rows: [
        "Eliment Disk",
        "Album Art",
        "Dummy Buttons",
        "Queue Display",
        "WaveForm",
        "Lyrics Engine",
        "Lyric Ball",
        "Visualizer",
        "Normalize Volume",
    ],
    anim_rows: [
        "Vis. Fluidity",
        "Waveform Style",
        "Disk Speed",
        "Playback Mode",
        "Vis. Degradation",
        "Vis. Viscosity",
        "Lyrics Alignment",
        "Lyrics Animation",
        "Language",
        "Output Device",
        "Crossfade",
        "Loudness Target",
        "Album Art",
    ],
    ref_rows: [
        "Open Settings",
        "Navigate Up",
        "Navigate Down",
        "Play / Pause",
        "Next Track",
        "Prev Track",
        "Toggle Repeat",
        "Toggle Shuffle",
        "Search Local",
        "Search Online",
        "Quit Application",
    ],
};

pub static TR: Strings = Strings {
    progress_bar: "ILERLEME",
    search_local: "YEREL ARAMA",
    search_online: "CEVRIMICI ARAMA",
    local_files: "YEREL SES DOSYALARI",
    online_results: "CEVRIMICI SONUCLAR",
    sort_prefix: "siralama",
    queue: "SIRA",
    queue_focused: "SIRA (odakta)",
    queue_empty: "SIRAYA PARCA EKLE",
    more_suffix: "daha",
    volume_bar: "SES SEVIYESI",
    play: "CAL",
    pause: "DURDUR",

    meta_name: "Ad",
    meta_artist: "Sanatci",
    meta_year: "yil",
    meta_sampling: "ornekleme",
    meta_type: "tur",
    meta_format: "bicim",
    meta_size: "boyut",
    meta_location: "konum",
    meta_channels: "kanal",

    no_track: "parca yuklenmedi - aramak icin /, calmak icin Enter",
    fetching_lyrics: "sozler getiriliyor ...",
    no_lyrics: "soz bulunamadi",
    resolving: "cozumleniyor/indiriliyor...",
    scanning: "kitaplik taraniyor...",
    no_music_path: "muzik klasoru yok - config.txt icine LocalMusicPath ekle",
    no_music_here: "hicbir sey bulunamadi - s ile KLASORLER sekmesinden klasor ekle",
    yt_dlp_missing: "yt-dlp PATH'te yok - cevrimici arama kapali",
    searching: "araniyor...",
    no_results: "sonuc yok",
    download_started: "indiriliyor...",
    playlist_saved: "parca kaydedildi",
    playlist_empty: "sirada da listede de kaydedilecek bir sey yok",
    playlist_nowhere: "kaydedilecek muzik klasoru yok",
    playlist_failed: "calma listesi yazilamadi",
    download_done: "kaydedildi:",
    settings_saved: "ayarlar kaydedildi",
    queued: "siraya eklendi",

    view_all: "tumu",
    view_liked: "begeniler",
    view_played: "en cok calan",
    view_recent: "son calanlar",
    liked: "begenildi",
    unliked: "begeni kaldirildi",
    help_title: "TUSLAR",
    help_close: "herhangi bir tus kapatir",
    help_mouse: "FARE",
    help_search: "kitaplikta ara",
    help_search_online: "cevrimici ara",
    help_play: "secileni cal",
    help_pause: "cal / duraklat",
    help_skip: "onceki / sonraki parca",
    help_seek: "geri / ileri sar",
    help_volume: "sesi azalt / arttir",
    help_modes: "karistir / tekrarla",
    help_queue: "siraya ekle / siradan cikar",
    help_panel: "liste ile sira arasinda gec",
    help_reorder: "sirayi yeniden dizle",
    help_like: "parcayi begen",
    help_view: "tumu, begeniler, en cok calan, son calanlar",
    help_sort: "ada, sanatciya, klasore, yeniye gore sirala",
    help_folder: "sadece bu klasor",
    help_artist: "sadece bu sanatci",
    help_clear: "aramayi ve filtreleri temizle",
    help_sleep: "uyku zamanlayicisi",
    help_playlist: "listeyi calma listesi olarak kaydet",
    help_lyrics: "sozleri one / geriye kaydir",
    help_download: "akisi kaydet",
    help_settings: "ayarlar",
    help_help: "bu ekran",
    help_quit: "cikis",
    help_mouse_disk: "duraklatmak icin kapaga tikla",
    help_mouse_skip: "onceki / sonraki",
    help_mouse_seek: "sarmak icin tikla ya da surukle",
    help_mouse_volume: "ses icin tikla ya da surukle",
    help_mouse_row: "secmek icin satira tikla",
    help_mouse_queue: "calmak icin tekrar tikla, siraya icin sag tikla",
    help_mouse_scroll: "tekerlek listeyi kaydirir",
    help_mouse_settings: "ayarlari acar",
    decode_failed: "bu dosya cozulemedi",
    lyric_shift: "sozler kaydirildi",
    sleep_off: "uyku zamanlayicisi kapali",
    sleep_set: "uyku suresi:",
    sleep_done: "uyku zamanlayicisi doldu",
    sort_name: "ad",
    sort_artist: "sanatci",
    sort_folder: "klasor",
    sort_recent: "yeni",
    mode_loop: "tekrar",
    mode_shuffle: "karisik",
    mode_stop: "bitince dur",

    tab_colors: "RENKLER",
    tab_onoff: "ACIK/KAPALI",
    tab_animation: "ANIMASYON",
    tab_eq: "EQ",
    tab_paths: "KLASORLER",
    tab_reference: "KISAYOLLAR",
    tab_about: "HAKKINDA",
    settings_title: "AYARLAR",
    settings_hint: "[TAB] Sekme | [\u{2191}\u{2193}\u{2190}\u{2192}] Gezin/Degistir | [ENTER] Duzenle | [S] Kaydet | [Q] Geri",
    paths_hint: "[ENTER] Duzenle | [A] Ekle | [D] Sil | [R] Yeniden Tara | [S] Kaydet | [Q] Geri",
    paths_add: "+ klasor veya calma listesi ekle",
    paths_missing: "bulunamadi",
    device_default: "sistem varsayilani",
    eq_preset: "Hazir ayar",
    eq_hint: "[\u{2191}\u{2193}] Bant | [\u{2190}\u{2192}] Kazanc | kaydiraca tikla | [0] Duz | [S] Kaydet | [Q] Geri",

    grp_border: "KENARLIK",
    grp_disk: "DISK",
    grp_metadata: "BILGI",
    grp_viz: "VIZ",
    grp_progress: "ILERLEME",
    grp_list: "LISTE",
    grp_queue: "SIRA",
    grp_lyrics: "SOZLER",

    col_top: "UST",
    col_bottom: "ALT",
    col_key: "ETIKET",
    col_val: "DEGER",
    col_left: "SOL",
    col_right: "SAG",
    col_played: "CALAN",
    col_pending: "KALAN",
    col_inactive_fg: "PASIF     ON",
    col_playing_fg: "CALAN     ON",
    col_cursor_fg: "IMLEC     ON",
    col_active_line_fg: "AKTIF SAT ON",
    col_active_word_fg: "AKTIF KEL ON",
    col_bg: "ZEMIN",
    preview_sample: "BU BIR ORNEK METINDIR",
    preview_song: "PARCA.MP3",
    preview_name: "AD : ",
    preview_lyric_a: "BU BIR ",
    preview_lyric_b: "ORNEK ",
    preview_lyric_c: "METINDIR",

    onoff_rows: [
        "Disk",
        "Albüm Kapagi",
        "Sahte Dugmeler",
        "Sira Paneli",
        "Dalga Formu",
        "Soz Motoru",
        "Soz Kuresi",
        "Gorsellestirici",
        "Ses Esitleme",
    ],
    anim_rows: [
        "Viz. Akiskanlik",
        "Dalga Bicimi",
        "Disk Hizi",
        "Calma Kipi",
        "Viz. Sonme",
        "Viz. Kivam",
        "Soz Hizalama",
        "Soz Animasyonu",
        "Dil",
        "Ses Cikisi",
        "Capraz Gecis",
        "Hedef Ses Duzeyi",
        "Album Kapagi",
    ],
    ref_rows: [
        "Ayarlari Ac",
        "Yukari Git",
        "Asagi Git",
        "Cal / Duraklat",
        "Sonraki Parca",
        "Onceki Parca",
        "Tekrar",
        "Karistir",
        "Yerel Arama",
        "Cevrimici Arama",
        "Cikis",
    ],
};
